config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
  validates :user_id, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  before_save { self.email = email.downcase }
  validates :username, presence: true, 
                        uniqueness: { case_sensitive: false}, 
                        length: { minimum: 2, maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
                        uniqueness: { case_sensitive: false}, 
                        length: { maximum: 105},
                        format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #prevent CSRF attackes by raising an exception
  #For APIs, you may want to use :null_session instead
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]

  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.page(params[:page])
  end
  
  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Article was successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:success] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
    @article.destroy
    flash[:danger] = "Article was successfully destroyed"
    redirect_to articles_path
  end

  private
    def set_article
      @article = Article.find(params[:id]) 
    end

    def article_params
      params.require(:article).permit(:title, :description)
    end

    def require_same_user
      if current_user != @article.user
        flash[:danger] = "You cannot do this action"
        redirect_to root_path
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end
  
  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "There was something wrong with your login information"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update]

  def index
    @users = User.page params[:page]
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the alpha blog #{@user.username}"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Your account was updated successfully"
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def show
    @user_articles = @user.articles.page(params[:page])
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end

    def set_user
      @user = User.find(params[:id])
    end

    def require_same_user
      if current_user != @user
        flash[:danger] = "You cannot do this action"
        redirect_to root_path
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "http://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "image-circle")
  end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
<div class="row">
  <div class="card col-8 offset-sm-2 mb-2">
      <h5 class="card-header">
        <%= link_to article.title, article_path(article) %>
      </h5>
      <div class="card-body card-text">
        <%= truncate(article.description, length: 100) %>
        <div class="article-meta-details">
          <small>
            created by: <%= article.user.username if article.user %>
            <%= time_ago_in_words(article.created_at) %> ago, 
            last updated: <%= time_ago_in_words(article.updated_at) %> ago
          </small>
        </div>
      </div>
      <% if logged_in? && current_user == article.user %>
      <div class="card-footer bg-white"> 
        <%= link_to 'Edit this article', edit_article_path(article), class: "btn btn-sm btn-primary"%> 
        <%= link_to 'Delete this article', article_path(article), method: :delete, data:{confirm: "Are you sure you want to delete this article?"}, class: "btn btn-sm btn-danger"%> 
      </div>
      <% end %>
  </div>
</div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>
<div class="container form-height">
  <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}, wrapper: :horizontal_form) do |f| %>
  <div class="form-group row">
    <div class="control-label col-sm-2">
      <%= f.label :title %>
    </div>
    <div class="col-sm-8">
      <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
    </div>
  </div>
  <div class="form-group row">
    <div class="control-label col-sm-2">
      <%= f.label :description %>
    </div>
    <div class="col-sm-8">
      <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
    </div>
  </div>
  <div class="form-group">
    <div class="offset-sm-2">
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  </div>
  <% end %>
  <div align="center">
    [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
  </div>
</div>

app/views/articles/edit.html.erb
<h2 align="center">Edit existing article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h2 align="center">Listing all article</h2>

<div align="center">
  <%= paginate @articles %>
</div>

<%= render 'article', obj: @articles %>

<div align="center">
  <%= paginate @articles %>
</div>

app/views/articles/new.html.erb
<h2 align="center">Create new article</h2>
<%= render 'form' %>

app/views/articles/show.html.erb
<div class="row">
  <div class="card col-8 offset-sm-2">
    <h5 class="card-header"><%= @article.title %></h5>
    <div class="card-body">
        <div class="card-text"> 
          <%= simple_format(@article.description) %>
        </div>
        <div class="article-meta-details">
          <small>
            created by: <%= @article.user.username if @article.user %>
            <%= time_ago_in_words(@article.created_at) %> ago, 
            last updated: <%= time_ago_in_words(@article.updated_at) %> ago
          </small>
        </div>
    </div>
    <div class="card-footer bg-white"> 
      <% if logged_in? && current_user == @article.user %>
        <%= link_to 'Edit this article', edit_article_path(@article), class: "btn btn-sm btn-primary"%> 
        <%= link_to 'Delete this article', article_path(@article), method: :delete, data:{confirm: "Are you sure you want to delete this article?"}, class: "btn btn-sm btn-danger"%> 
      <% end %>
      <%= link_to "View all articles", articles_path, class: "btn btn-sm btn-success" %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <p>
      <small>
        Copyright &copy; <a href="https://www.udemy.com">The complete Ruby on Rails Developer by A</a>
      </small>
      <small class="float-right"><%=link_to "About", about_path %></small>
    </p>
  <div class="float-left card">
    <p><%= debug(params) if Rails.env.development? %></p>
  </div>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="container mb-3">
  <% flash.each do |name, msg| %>
  <div class="alert-<%= "#{name}"%>">
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color:#08088A";>
  <%= link_to "Alpha-blog", root_path, class: "navbar-brand", id: "logo"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to "All Articles", articles_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "All Users", users_path, class:"nav-link" %>
      </li>
    </ul>
    <ul class="navbar-nav">
      <% if logged_in? %>
        <li class="nav-item dropdown mr-auto">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            My Article
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%=link_to "New Articles", new_article_path, class:"dropdown-item"%>

            <a class="dropdown-item" href="#"></a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
      <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0 mr-auto">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    <ul class="navbar-nav">
      <% if logged_in? %>
        <li class="nav-item dropdown mr-auto">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            My Info
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%=link_to "New Articles", new_article_path, class:"dropdown-item"%>
            <%=link_to "Log out", logout_path, method: :delete, class:"dropdown-item" %>
            <a class="dropdown-item" href="#"></a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
      <% else %>
        <li class="nav-item float-right">
          <%= link_to "Log in", login_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", signup_path, class:"nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation'%>
    <%= render 'layouts/messages'%>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is the aboutpage</h1>
<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<div class="jumbotron jumbotron-extend">
  <div class="container-fluid jumbotron-container">
    <h1>ALPHA BLOG</h1>
    <%= link_to 'Sign up now', signup_path, class: "btn btn-primary btn-lg" %> 
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="card col-6 offset-sm-3 alert-danger">
      <h5 class="card-heading">
          <%= pluralize(obj.errors.count, "error") %>
          prohibited this article from being saved:
      </h5>
        <div class="card-body card-text">
          <ul>
            <% obj.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>
<div class="container form-height">
  <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}, wrapper: :horizontal_form) do |f| %>
  <div class="form-group row">
    <div class="control-label col-sm-2">
      <%= f.label :username %>
    </div>
    <div class="col-sm-8">
      <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
    </div>
  </div>
  <div class="form-group row">
    <div class="control-label col-sm-2">
      <%= f.label :email %>
    </div>
    <div class="col-sm-8">
      <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
    </div>
  </div>
  <div class="form-group row">
    <div class="control-label col-sm-2">
      <%= f.label :password %>
    </div>
    <div class="col-sm-8">
      <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
    </div>
  </div>
  <div class="form-group">
    <div class="offset-sm-2">
      <%= f.submit(@user.new_record? ? "Sign up" : "Update your account", class: 'btn btn-primary' )%>
    </div>
  </div>
  <% end %>
  <div align="center">
    [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
  </div>
</div>

app/views/users/edit.html.erb
<h2 align="center">Edit your account </h2>

<%= render 'form' %>

app/views/users/index.html.erb
<h2 align="center">All Alpha Bloggers</h2>

<div align="center">
  <%= paginate @users%>
</div>

<% @users.each do |user| %>
  <div class="row">
    <div class="card col-4 offset-sm-4 mb-2 text-center">
        <h5 class="card-header">
          <%= link_to gravatar_for(user), user_path(user) %>
        </h5>
        <div class="card-body card-text">
          <%= link_to user.username, user_path(user) %>
          <div class="article-meta-details">
            <small><%= pluralize(user.articles.count, "article") if user.articles %></small> 
          </div>
        </div>
    </div>
  </div>
<% end %>

<div align="center">
  <%= paginate @users%>
</div>

app/views/users/new.html.erb
<h2 align="center">Signup for Alpha Blog </h2>

<%= render 'form' %>

app/views/users/show.html.erb
<h2 align="center"><%= @user.username %>'s Page</h2>
<p align="center"><%= gravatar_for @user %></p>

<div class="row">
  <div class="col-8 offset-sm-2">
    <h5 align="center">Articles</h5>
      <%= paginate @user_articles %>
    <%= render 'articles/article', obj: @user_articles %>
  </div>
</div>

 <%= paginate @user_articles %>